# Generated by Django 4.0 on 2022-01-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='img',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
